name: GitHub Shemaspy test
on: [push]
jobs:
  schemaspy:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - name: compose-run
          shell: bash
          run: |
            docker-compose up -d