name: GitHub Shemaspy test
on: [push]
jobs:
  schemaspy:
    runs-on: ubuntu-latest
    services:
        mysql:
          image: mysql:5.7
          options: >-
            --health-cmd "mysqladmin ping -h localhost"
            --health-interval 20s
            --health-timeout 10s
            --health-retries 10
          env:
            MYSQL_USER: django
            MYSQL_PASSWORD: django
          ports:
            - 3306
    steps:
        - uses: actions/checkout@v2
        - name: compose-run
        shell: bash
        run: |
          docker-compose up -d