name: GitHub Shemaspy test
on: [push]
jobs:
  schemaspy:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - name: file-check-init
          shell: bash
          run: |
            ls
        - name: compose-run
          shell: bash
          run: |
            docker-compose up -d
            sleep 60s
        - name: migrate
          shell: bash
          run: |
            docker exec -t test-django python manage.py migrate
            sleep 60s
        - name: compose-schemaspy
          shell: bash
          run: |
            sudo mkdir -p schema
            sudo chmod 777 schema
            docker-compose -f docker-compose.yml up --build schemaspy
            sleep 60s
        - name: file-check-1
        shell: bash
        run: |
            ls -a
        - name: file-check-2
          shell: bash
          run: |
            ls -a schemaspy/
            ls -a schemaspy/output/
        - name: file-check-3
          shell: bash
          run: |
            ls -a schemaspy/output/