name: GitHub Shemaspy test
on: [push]
jobs:
  schemaspy:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - name: file-check-init
          shell: bash
          run: |
            sudo mkdir -p schemaspy
            sudo mkdir -p schemaspy/output
            sudo chmod 777 schemaspy
            sudo chmod 777 schemaspy/output
            ls
        - name: compose-run
          shell: bash
          run: |
            docker-compose up -d
            sleep 60s
        - name: migrate
          shell: bash
          run: |
            docker exec -t test-django python manage.py migrate
            sleep 60s
        - name: compose-schemaspy
          shell: bash
          run: |
          docker run --rm --net=host -v $PWD/output:/output -v $PWD/schemaspy.properties:/schemaspy.properties schemaspy/schemaspy:snapshot
            sleep 60s
        - name: file-check-1
          shell: bash
          run: |
            ls -a
        - name: file-check-2
          shell: bash
          run: |
            ls -a output/
        - uses: montudor/action-zip@v0.1.1
          with:
            args: zip -qq -r output.zip output
        - name: file-check-4
          shell: bash
          run: |
            ls -a schemaspy/
        - name: Upload to slack channel
          uses: adrey/slack-file-upload-action@master
          with:
            token: ${{ secrets.SLACK_TOKEN }}
            path: output.zip
            channel: github-actions-test