name: GitHub Shemaspy test
on: [push]
jobs:
  schemaspy:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - name: file-check-init
          shell: bash
          run: |
            sudo mkdir -p schemaspy
            sudo mkdir -p schemaspy/output
            sudo chmod 777 schemaspy
            sudo chmod 777 schemaspy/output
            ls
        - name: compose-run
          shell: bash
          run: |
            docker-compose up -d
            sleep 60s
        - name: migrate
          shell: bash
          run: |
            docker exec -t test-django python manage.py migrate
            sleep 60s
        - name: compose-schemaspy
          shell: bash
          run: |
            docker-compose -f docker-compose.yml up --build schemaspy
            sleep 60s
        - name: file-check-1
          shell: bash
          run: |
            ls -a
        - name: file-check-2
          shell: bash
          run: |
            ls -a schemaspy/
            ls -a schemaspy/output/
        - name: file-check-3
          shell: bash
          run: |
            ls -a schemaspy/output/
        - uses: montudor/action-zip@v0.1.1
          with:
            args: zip -qq -r schemaspy/output.zip schemaspy/output
          shell: bash
          run: |
            docker-compose -f docker-compose.yml up --build schemaspy
            sleep 60s
        - name: file-check-4
          shell: bash
          run: |
            ls -a schemaspy/
            - name: Upload to slack
        - uses: adrey/slack-file-upload-action@master
          with:
            token: xoxe.xoxp-1-Mi0yLTE4ODIwMDkwOTU3MzAtMTg5NDYyMjMwMTc3Ny0zNjUyNjI3Nzc2MzQxLTM2NTU1Mzg2MzM0MTAtYmQzMDdjMDdhNTVkNDE3NzI0NzIzMWQwNTQxZDQxNDI0YmJiOTUwNDA2ODZlMTNlOTIwOWUzMzM4MmFlMWUyNQ
            path: schemaspy/output.zip
            channel: github-actions-test

            